version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd citibank-practice-frontend
      - npm ci

  build:
    commands:
      - echo "Running frontend tests..."
      - npm test
